#ifndef SPRITE_AI_SHOPKEEPER_H
#define SPRITE_AI_SHOPKEEPER_H

#include "types.h"
#include "oam.h"

void BeginBossTreasureChestDespawn(void);
void BeginShopkeeperExit(void);
void BeginShopkeeperItemWait(void);
void BeginShopkeeperPostItemIdle(void);
void BeginShopkeeperTransformationReturn(void);
void BeginShopkeeperTransitionReturn(void);
void FadeLargeLipsKissEffect(void);
void FinishBlackDogAttack(void);
void FinishShopkeeperBugleSetup(void);
void FinishShopkeeperVizormanSetup(void);
void GrowLargeLipsKissEffect(void);
void InitAppleBomb(void);
void InitBigFist(void);
void InitBlackDog(void);
void InitBlackDragon(void);
void InitBlackDragonFire(void);
void InitBlastCannon(void);
void InitBlastCannonball(void);
void InitBossTreasureChest(void);
void InitBugle(void);
void InitLargeLips(void);
void InitLargeLipsKissEffect(void);
void InitPurchasedItemDisplay(void);
void InitShopkeeper(void);
void InitShopkeeperTransition(void);
void InitVizorman(void);
void InitVizormanBeamCore(void);
void InitVizormanBeamGlow(void);
void MoveBlackDragonFireIntoPosition(void);
void MoveBlastCannonWithShopkeeper(void);
void MoveBugleWithShopkeeper(void);
void MoveLargeLipsIntoPosition(void);
void MoveLargeLipsKissEffect(void);
void MoveShopkeeperAppleBombIntoPosition(void);
void MoveShopkeeperBlastCannonIntoPosition(void);
void MoveShopkeeperBugleIntoPosition(void);
void MoveShopkeeperSmileOffscreen(void);
void MoveShopkeeperToSmilePosition(void);
void MoveShopkeeperTransformationIntoPosition(void);
void MoveShopkeeperVizormanIntoPosition(void);
void MoveVizormanWithShopkeeper(void);
void PlayBlackDragonAttackSoundCue(void);
void PlayShopkeeperCarrySoundCue(void);
void PlayShopkeeperReadySoundCue(void);
void ReplaceShopkeeperWithTransitionSprite(void);
void RotateShopkeeperSmile(void);
void SelectBugleNoteAnimation(void);
void SetupShopkeeperSelectedItem(void);
void ShopItemFollowShopkeeper(void);
void ShopkeeperFollowWario(void);
void ShopkeeperUpdateGraphicsScript(const u8 *script);
void ShrinkShopkeeperSmile(void);
void SpawnBossTreasureRewards(void);
void SpawnShopkeeperTransformationItem(void);
void SpawnVizormanBeamActors(void);
void SpriteAppleBomb(void);
void SpriteBigFist(void);
void SpriteBlackDog(void);
void SpriteBlackDragon(void);
void SpriteBlackDragonFire(void);
void SpriteBlastCannon(void);
void SpriteBlastCannonball(void);
void SpriteBossTreasureChest(void);
void SpriteBugle(void);
void SpriteBugleNote(void);
void SpriteLargeLips(void);
void SpriteLargeLipsKissEffect(void);
void SpritePurchasedItemDisplay(void);
void SpriteShopEffectLong(void);
void SpriteShopEffectShortA(void);
void SpriteShopEffectShortB(void);
void SpriteShopkeeper(void);
void SpriteShopkeeperTransition(void);
void SpriteVizorman(void);
void SpriteVizormanBeamCore(void);
void SpriteVizormanBeamGlow(void);
void StartAppleBombExplosion(void);
void StartAppleBombFuse(void);
void StartBigFistAttack(void);
void StartBlackDogAttack(void);
void StartBlastCannonCountdown(void);
void StartBossTreasureChestOpening(void);
void StartBugleAttack(void);
void StartLargeLipsKiss(void);
void StartShopkeeperBlastCannonAttack(void);
void FinishShopkeeperTransitionWait(void);
void StartShopkeeperSmileDrop(void);
void StartShopkeeperSmileJump(void);
void StartShopkeeperSmilePose(void);
void StartShopkeeperTransitionLanding(void);
void StartVizormanBeamCoreActive(void);
void StartVizormanBeamCoreEnd(void);
void StartVizormanBeamGlow(void);
void ToggleLargeLipsKissEffectFlip(void);
void ToggleLargeLipsKissEffectFlipReverse(void);
void UpdateAppleBombBurst(void);
void UpdateAppleBombFlight(void);
void UpdateAppleBombFuse(void);
void UpdateBigFistAttack(void);
void UpdateBigFistCollision(void);
void UpdateBlackDogAttack(void);
void UpdateBlackDogCollision(void);
void MoveBlackDragonIntoAttackPosition(void);
void UpdateBlackDragonAttack(void);
void UpdateBlackDragonAttackReturn(void);
void UpdateBlackDragonBob(void);
void UpdateBlackDragonFireAttack(void);
void UpdateBlackDragonFireCollision(void);
void UpdateBlackDragonFireLifetime(void);
void UpdateBlastCannonCountdown(void);
void UpdateBlastCannonballBurst(void);
void UpdateBlastCannonballFlight(void);
void UpdateBossTreasureChestOpening(void);
void UpdateBossTreasureChestRise(void);
void UpdateBossTreasureRewards(void);
void UpdateBugleAttack(void);
void UpdateBugleNoteAffine(void);
void UpdateLargeLipsCollision(void);
void UpdateLargeLipsKiss(void);
void UpdateLargeLipsRetreat(void);
void UpdateShopkeeperAppleBombPresentation(void);
void UpdateShopkeeperCommonAnimation(void);
void UpdateShopkeeperExit(void);
void UpdateShopkeeperItemWait(void);
void UpdateShopkeeperPostItemIdle(void);
void UpdateShopkeeperSmileDrop(void);
void UpdateShopkeeperSmileJump(void);
void UpdateShopkeeperSmilePose(void);
void UpdateShopkeeperTransitionDeparture(void);
void UpdateShopkeeperTransitionFall(void);
void UpdateShopkeeperTransitionRun(void);
void UpdateVizormanBeamCoreEnd(void);
void UpdateVizormanBeamGlowLifetime(void);
void UpdateVizormanBeamPalette(void);
void WaitBossTreasureChestDespawn(void);
void WaitForShopkeeperBlastCannonReady(void);
void WaitForShopkeeperBugleReady(void);
void WaitForShopkeeperRoomReady(void);
void WaitForShopkeeperSmileEffect(void);
void WaitForShopkeeperVizormanReady(void);
void WaitForWarioTransitionPose(void);

extern const struct AnimationFrame sSelectedShopItemOam[];
extern const struct AnimationFrame sShopEffectShortAOam[];
extern const struct AnimationFrame sBossTreasureChestOpeningOam[];
extern const struct AnimationFrame sShopEffectLongOam[];
extern const struct AnimationFrame sShopEffectShortBOam[];
extern const struct AnimationFrame sBossTreasureChestDespawnOam[];
extern const struct AnimationFrame sBossTreasureChestInitialOam[];
extern const struct AnimationFrame sBossTreasureRewardOam[];
extern const struct AnimationFrame sAppleBombIdleOam[];
extern const struct AnimationFrame sAppleBombFuseOam[];
extern const struct AnimationFrame sAppleBombExplosionOam[];
extern const struct AnimationFrame sPurchasedAppleBombOam[];
extern const struct AnimationFrame sBlastCannonCountdownOam[];
extern const struct AnimationFrame sPurchasedBlastCannonOam[];
extern const struct AnimationFrame sBlastCannonballOam[];
extern const struct AnimationFrame sBlastCannonIdleOam[];
extern const struct AnimationFrame sVizormanIdleOam[];
extern const struct AnimationFrame sVizormanBeamCoreInitialOam[];
extern const struct AnimationFrame sVizormanBeamCoreEndOam[];
extern const struct AnimationFrame sVizormanBeamGlowInitialOam[];
extern const struct AnimationFrame sVizormanBeamCoreActiveOam[];
extern const struct AnimationFrame sVizormanBeamGlowStartOam[];
extern const struct AnimationFrame sVizormanBeamGlowActiveOam[];
extern const struct AnimationFrame sBugleIdleOam[];
extern const struct AnimationFrame sBugleAttackOam[];
extern const struct AnimationFrame sBugleNote1Oam[];
extern const struct AnimationFrame sBugleNote2Oam[];
extern const struct AnimationFrame sBugleNote3Oam[];
extern const struct AnimationFrame sBugleNote4Oam[];
extern const struct AnimationFrame sBugleNote5Oam[];
extern const struct AnimationFrame sBugleNote6Oam[];
extern const struct AnimationFrame sBugleNote7Oam[];
extern const struct AnimationFrame sBugleNote8Oam[];
extern const struct AnimationFrame sBugleNote9Oam[];
extern const struct AnimationFrame sBugleNote10Oam[];
extern const struct AnimationFrame sBlackDogIdleOam[];
extern const struct AnimationFrame sPurchasedBlackDogOam[];
extern const struct AnimationFrame sLargeLipsIdleOam[];
extern const struct AnimationFrame sLargeLipsKissEffectAOam[];
extern const struct AnimationFrame sLargeLipsKissEffectBOam[];
extern const struct AnimationFrame sLargeLipsKissEffectCOam[];
extern const struct AnimationFrame sLargeLipsMoveOam[];
extern const struct AnimationFrame sLargeLipsKissOam[];
extern const struct AnimationFrame sBigFistIdleOam[];
extern const struct AnimationFrame sPurchasedBigFistOam[];
extern const struct AnimationFrame sBlackDragonAttackOam[];
extern const struct AnimationFrame sBlackDragonFireOam[];
extern const struct AnimationFrame sPurchasedBlackDragonOam[];
extern const struct AnimationFrame sBlackDragonIdleOam[];
extern const struct AnimationFrame sBlackDragonMoveOam[];
extern const struct AnimationFrame sShopkeeperIdleOam[];
extern const struct AnimationFrame sShopkeeperTransitionLandingOam[];
extern const struct AnimationFrame sShopkeeperTransitionRunOam[];
extern const struct AnimationFrame sShopkeeperSmileJumpOam[];
extern const struct AnimationFrame sShopkeeperSmileWaitOam[];
extern const struct AnimationFrame sShopkeeperSmileDropOam[];
extern const struct AnimationFrame sShopkeeperTransitionDepartureOam[];
extern const struct AnimationFrame sShopkeeperSmileFinishOam[];
extern const struct AnimationFrame sShopkeeperTransitionWaitOam[];
extern const struct AnimationFrame sShopkeeperTransitionInitialOam[];
extern const struct AnimationFrame sShopkeeperSmilePoseOam[];
extern const struct AnimationFrame sShopkeeperTransitionImpactOam[];
extern const struct AnimationFrame sShopkeeperSmilePositionedOam[];
extern const struct AnimationFrame sShopkeeperSmileExitOam[];

extern const u8 sShopkeeperDefaultGraphicsScript[];
extern const u8 sShopkeeperAppleBombGraphicsScript[];
extern const u8 sShopkeeperVizormanGraphicsScript[];
extern const u8 sShopkeeperCarryItemGraphicsScript[];
extern const u8 sShopkeeperItemApproachGraphicsScript[];
extern const u8 sVizormanFollowGraphicsScript[];
extern const u8 sShopkeeperTransformationGraphicsScript[];
extern const u8 sAppleBombPresentationGraphicsScript[];
extern const u8 sShopkeeperItemReadyGraphicsScript[];
extern const u8 sShopkeeperAttackGraphicsScript[];
extern const s16 sShopkeeperSmileVelocityTable[];
extern const s16 sShopkeeperTransitionFallVelocityTable[];
extern const s16 sAppleBombPassage1FlightPath[];
extern const s16 sAppleBombPassage2FlightPath[];
extern const s16 sAppleBombPassage3FlightPath[];
extern const s16 sAppleBombPassage4FlightPath[];
extern const s16 sAppleBombPassage5FlightPath[];
extern const s16 sAppleBombDefaultFlightPath[];
extern const s16 sBlastCannonballPassage1FlightPath[];
extern const s16 sBlastCannonballPassage2FlightPath[];
extern const s16 sBlastCannonballPassage3FlightPath[];
extern const s16 sBlastCannonballPassage4FlightPath[];
extern const s16 sBlastCannonballPassage5FlightPath[];
extern const s16 sBlastCannonballDefaultFlightPath[];
extern const s16 sBlackDogMovementPath[];
extern const s16 sLargeLipsMovementPath[];
extern const s16 sBigFistMovementPath[];
extern const s16 sBlackDragonBobPath[];
extern const s16 sBlackDragonAttackReturnPath[];
extern const s16 sBossTreasureOpeningVelocityTable[];
extern const s16 sBossTreasureRiseVelocityTable[];
extern const u16 sVizormanBeamPaletteFrames[];
extern const u16 sBugleNoteAffineAngleTable[];
extern const u16 sShopkeeperItemTiles[];
extern const s16 sSpriteGravityVelocityTable[];
extern const u16 sSpriteAffineScaleTable[][2];
extern const void *sShopkeeperGraphicsFramePointers[];

#endif /* SPRITE_AI_SHOPKEEPER_H */
