#ifndef WARIO_NORMAL_H
#define WARIO_NORMAL_H

#include "global_data.h"
#include "wario.h"


extern s8 gWarioCollisionDamageFlag;
extern s16 gWarioTileHorizontalSpeed;
extern s16 gWarioTileVerticalSpeed;

extern const struct WarioPoseProperty sWarioNormalPoseProperties[];
extern const u16 sWarioCollisionPointTable[];
extern const u16 sWarioCollisionSideTable[];
extern u16 sWarioTileHorizontalSpeedTable[];
extern u16 sWarioTileVerticalSpeedTable[];
extern const u8 sWarioLiftingSpriteStateTable[];
extern const u8 sWarioLiftingHeavySpriteStateTable[];
extern const u8 sWarioChargingThrowStateTable[];
extern const u8 sWarioWeakThrowStateTable[];
extern const u8 sWarioChargedThrowStateTable[];
extern const u8 sWarioTurningThrowStateTable[];

extern const struct WarioAnimationFrame *const sWarioPoseAnimationTable[];
extern const struct WarioAnimationFrame *const sWarioCarryingAnimationTable[];
extern const struct WarioAnimationFrame *const sWarioUpwardThrowAnimationTable[];
extern const struct WarioAnimationFrame *const sWarioAirborneAnimationTable[];
extern const struct WarioAnimationFrame *const sWarioIdleInputAnimationTable[];

extern const struct WarioAnimationFrame sWarioWalkingAnimation[];
extern const struct WarioAnimationFrame sWarioFastWalkingAnimation[];
extern const struct WarioAnimationFrame sWarioTurningAnimation[];
extern const struct WarioAnimationFrame sWarioStandingAnimation[];
extern const struct WarioAnimationFrame sWarioJumpingAnimation[];
extern const struct WarioAnimationFrame sWarioCrawlingAnimation[];
extern const struct WarioAnimationFrame sWarioCrouchJumpAnimation[];
extern const struct WarioAnimationFrame sWarioStoppingFromDashAnimation[];
extern const struct WarioAnimationFrame sWarioStartingRollAnimation[];
extern const struct WarioAnimationFrame sWarioJumpingOutOfRollAnimation[];
extern const struct WarioAnimationFrame sWarioRollingAnimation[];
extern const struct WarioAnimationFrame sWarioEnteringPipeAnimation[];
extern const struct WarioAnimationFrame sWarioTakingDamageAnimation[];
extern const struct WarioAnimationFrame sWarioRollingMidairAnimation[];
extern const struct WarioAnimationFrame sWarioShoulderBashAnimation[];
extern const struct WarioAnimationFrame sWarioDashAttackAnimation[];
extern const struct WarioAnimationFrame sWarioShoulderBashJumpAnimation[];
extern const struct WarioAnimationFrame sWarioGroundPoundAnimation[];
extern const struct WarioAnimationFrame sWarioGroundPoundLandingAnimation[];
extern const struct WarioAnimationFrame sWarioSuperGroundPoundLandingAnimation[];
extern const struct WarioAnimationFrame sWarioLiftingSpriteAnimation[];
extern const struct WarioAnimationFrame sWarioLiftingHeavySpriteAnimation[];
extern const struct WarioAnimationFrame sWarioChargingThrowAnimation[];
extern const struct WarioAnimationFrame sWarioWeakThrowAnimation[];
extern const struct WarioAnimationFrame sWarioChargedThrowAnimation[];
extern const struct WarioAnimationFrame sWarioWeakThrowUpwardsAnimation[];
extern const struct WarioAnimationFrame sWarioTurningThrowAnimation[];
extern const struct WarioAnimationFrame sWarioVerticalClimbingAnimation[];
extern const struct WarioAnimationFrame sWarioHorizontalFenceAnimation[];
extern const struct WarioAnimationFrame sWarioDoorAnimation[];
extern const struct WarioAnimationFrame sWarioEnteringDoorAnimation[];
extern const struct WarioAnimationFrame sWarioUnknown53Animation[];
extern const struct WarioAnimationFrame sWarioDumbbellAnimation[];
extern const struct WarioAnimationFrame sWarioBarbellAnimation[];
extern const struct WarioAnimationFrame sWarioBarbellEndingAnimation[];
extern const struct WarioAnimationFrame sWarioJumpRopeAnimation[];
extern const struct WarioAnimationFrame sWarioUnknown60Animation[];
extern const struct WarioAnimationFrame sWarioFlexingAnimation[];
extern const struct WarioAnimationFrame sWarioUnknown66Animation[];
extern const struct WarioAnimationFrame sWarioUnknown67Animation[];
extern const struct WarioAnimationFrame sWarioUnknown68Animation[];
extern const struct WarioAnimationFrame sWarioUnknown69Animation[];
extern const struct WarioAnimationFrame sWarioUnknown70Animation[];
extern const struct WarioAnimationFrame sWarioUnknown71Animation[];
extern const struct WarioAnimationFrame sWarioUnknown75Animation[];
extern const struct WarioAnimationFrame sWarioUnusedPose76Animation[];
extern const struct WarioAnimationFrame sWarioUnusedPose77Animation[];

extern const struct WarioEffectFrame sWarioGroundPoundLandingAfterimageFrames[];

extern const u16 sWarioShoulderBashPalette[];
extern const u16 sWarioDashAttackPaletteFrames[];
extern const u16 sWarioDamageFlashPalette[];
extern const u16 sWarioUnusedPose76AlternatePalette[];
extern const u16 sWarioGroundPoundSecondaryPalette[];
extern const u16 *const sWarioGroundPoundPaletteFrames[];
extern const u16 sWarioUnusedPose76Palette[];
extern const u16 sWarioChargedThrowPaletteFrames[];
extern const u16 sWarioDumbbellSecondaryPalette[];
extern const u16 sWarioDoorAndBarbellSecondaryPalette[];
extern const u16 sWarioFlexingPalette[];

u8 UpdateNormalWarioPose(void);
u8 UpdateNormalWarioWalking(void);
u8 UpdateNormalWarioTurning(void);
u8 UpdateNormalWarioStanding(void);
u8 UpdateNormalWarioJumping(void);
u8 UpdateNormalWarioFalling(void);
u8 UpdateNormalWarioCrouching(void);
u8 UpdateNormalWarioCrouchSliding(void);
u8 UpdateNormalWarioCrawling(void);
u8 UpdateNormalWarioTurningCrouched(void);
u8 UpdateNormalWarioCrouchJump(void);
u8 UpdateNormalWarioSlidingOnIce(void);
u8 UpdateNormalWarioStoppingFromDash(void);
u8 UpdateNormalWarioStartingRoll(void);
u8 UpdateNormalWarioJumpingOutOfRoll(void);
u8 UpdateNormalWarioRolling(void);
u8 UpdateNormalWarioRollingJump(void);
u8 UpdateNormalWarioStunned(void);
u8 UpdateNormalWarioEnteringPipe(void);
u8 UpdateNormalWarioTakingDamage(void);
u8 UpdateNormalWarioRollingMidair(void);
u8 UpdateNormalWarioShoulderBash(void);
u8 UpdateNormalWarioDashAttack(void);
u8 UpdateNormalWarioShoulderBashJump(void);
u8 UpdateNormalWarioDashAttackJump(void);
u8 UpdateNormalWarioShoulderBashBonk(void);
u8 UpdateNormalWarioGroundPound(void);
u8 UpdateNormalWarioGroundPoundLanding(void);
u8 UpdateNormalWarioLandingOnEnemy(void);
u8 UpdateNormalWarioLiftingSprite(void);
u8 UpdateNormalWarioLiftingHeavySprite(void);
u8 UpdateNormalWarioChargingThrow1(void);
u8 UpdateNormalWarioChargingThrow2(void);
u8 UpdateNormalWarioWeakThrow(void);
u8 UpdateNormalWarioChargedThrow(void);
u8 UpdateNormalWarioWeakThrowUpwards(void);
u8 UpdateNormalWarioTurningWhileChargingThrow(void);
u8 UpdateNormalWarioClimbingLadder(void);
u8 UpdateNormalWarioIdleOnLadder(void);
u8 UpdateNormalWarioSlidingDownLadder(void);
u8 UpdateNormalWarioClimbingFenceVertical(void);
u8 UpdateNormalWarioClimbingFenceHorizontal(void);
u8 UpdateNormalWarioIdleOnFence(void);
u8 UpdateNormalWarioUnknown46(void);
u8 UpdateNormalWarioUnknown48(void);
u8 UpdateNormalWarioEnteringDoor(void);
u8 UpdateNormalWarioExitingDoor(void);
u8 UpdateNormalWarioLookingUp(void);
u8 UpdateNormalWarioUnknown52(void);
u8 UpdateNormalWarioUnknown53(void);
u8 UpdateNormalWarioDumbbells(void);
u8 UpdateNormalWarioBarbell(void);
u8 UpdateNormalWarioBarbellEnding(void);
u8 UpdateNormalWarioUnknown58(void);
u8 UpdateNormalWarioJumpRope(void);
u8 UpdateNormalWarioUnknown60(void);
u8 UpdateNormalWarioBossDefeatedMidair(void);
u8 UpdateNormalWarioBossDefeated(void);
u8 UpdateNormalWarioFlexing(void);
u8 UpdateNormalWarioUnknown66(void);
u8 UpdateNormalWarioUnknown67(void);
u8 UpdateNormalWarioUnknown68(void);
u8 UpdateNormalWarioUnknown69(void);
u8 UpdateNormalWarioUnknown70(void);
u8 UpdateNormalWarioUnknown71(void);
u8 UpdateNormalWarioUnknown72(void);
u8 UpdateNormalWarioUnknown73(void);
u8 UpdateNormalWarioUnknown74(void);
u8 UpdateNormalWarioUnknown75(void);
u8 UpdateNormalWarioUnused76(void);
u8 UpdateNormalWarioUnused77(void);
u8 UpdateNormalWarioUnused78(void);
void ApplyNormalWarioPoseTransition(u8 pose);
void ResumeNormalWarioAfterCollision(void);
void ResolveNormalWarioPoseCollision(void);
void SetNormalWarioPose(u8 arg0);
void UpdateNormalWarioMovement(void);
void ResolveNormalWarioCollision(void);
u8 CheckWarioTileCollision(u32 xPosition, u32 yPosition, u16 *newYPosition, u16 *newXPosition, u16 *inWater);
u32 CheckWarioHorizontalCollision(u32 side, u16 *newXPosition, u32 verticalOffset);
int CheckWarioVerticalCollision(u32 index, u32 offset, u32 mode);
u32 CheckWarioPointCollision(u32 index, u32 yPosition, u16 *secondaryResult);
u8 ResolveWarioStandardCollision(void);
u8 ResolveWarioLandingCollision(void);
u8 ResolveWarioCeilingCollision(void);
u8 ResolveWarioFloorCollision(void);
u8 ResolveWarioTileEdgeCollision(void);
u8 ResolveWarioLadderCollision(void);
u8 ResolveWarioVerticalFenceCollision(void);
u8 ResolveWarioHorizontalFenceCollision(void);
void DrawNormalWario(u8 direction);
void UpdateWarioMusicEffects(void);
void UpdateWarioHitbox(void);
u32 CheckWarioReactionCollision(u8 reaction);
void UpdateWarioTileMovement(void);
u8 CheckWarioTileMovement(void);

#endif
