#!/usr/bin/env python3
from __future__ import annotations
import argparse, re, shutil, sys
from pathlib import Path

ROM_BASE=0x08000000
BLOB_RE=re.compile(r'^\s*baserom_blob\s+0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*$')
GLOBAL_RE=re.compile(r'^\s*\.global\s+([A-Za-z_]\w*)\s*$')
LABEL_RE=re.compile(r'^\s*([A-Za-z_]\w*):\s*$')

class E(Exception): pass

def hx(s): return int(s,0)
def fmt_bytes(data):
    out=[]
    for i in range(0,len(data),16):
        out.append('    '+', '.join(f'0x{x:02X}' for x in data[i:i+16])+',')
    return '\n'.join(out)

def main():
    ap=argparse.ArgumentParser(description='Safely extract a prefix of a pure baserom_blob ASM object into a Method 3 C region.')
    ap.add_argument('asm_file', type=Path)
    ap.add_argument('split_end', type=hx, help='ROM offset or address where generated prefix ends, e.g. 0x41000C')
    ap.add_argument('--rom', type=Path, default=Path('baserom_us.gba'))
    ap.add_argument('--linker', type=Path, default=Path('linker.ld'))
    ap.add_argument('--output', type=Path)
    ap.add_argument('--apply', action='store_true')
    a=ap.parse_args()
    root=Path.cwd(); asm=a.asm_file
    if not asm.exists(): raise E(f'ASM file not found: {asm}')
    if not a.rom.exists(): raise E(f'ROM not found: {a.rom}')
    text=asm.read_text(); lines=text.splitlines(True)
    segs=[]; pending=None; unsafe=[]
    for n,line in enumerate(lines,1):
        s=line.split('@',1)[0].strip()
        if not s or s.startswith('/*') or s.startswith('*') or s.startswith('*/'): continue
        m=GLOBAL_RE.match(s)
        if m: continue
        m=LABEL_RE.match(s)
        if m: pending=m.group(1); continue
        m=BLOB_RE.match(s)
        if m:
            st,en=int(m.group(1),16),int(m.group(2),16)
            segs.append((st,en,pending)); pending=None; continue
        if re.match(r'^\.(include|section|align|balign|p2align)\b',s): continue
        unsafe.append(f'line {n}: {s}')
    if unsafe: raise E('ASM is not pure baserom_blob data:\n  '+'\n  '.join(unsafe[:10]))
    if not segs: raise E('No baserom_blob segments found')
    segs.sort(); start=segs[0][0]; end=segs[-1][1]
    split=a.split_end-ROM_BASE if a.split_end>=ROM_BASE else a.split_end
    if split not in {e for _,e,_ in segs}: raise E(f'0x{split:X} is not a baserom_blob end boundary')
    if not (start < split < end): raise E(f'split must be inside 0x{start:X}-0x{end:X}')
    prefix=[x for x in segs if x[1] <= split]; suffix=[x for x in segs if x[0] >= split]
    if len(prefix)+len(suffix)!=len(segs): raise E('split crosses a segment')
    out=a.output or Path(f'src/data/sprite_data_{start:06X}_{split:06X}.c')
    rom=a.rom.read_bytes()
    c=['#include "types.h"','#include "oam.h"','', '/*',f' * Shared sprite data region: 0x{ROM_BASE+start:08X} - 0x{ROM_BASE+split:08X}',' * Generated by split_blob_region.py from a linked ASM prefix.',' */','']
    used=set()
    for st,en,label in prefix:
        name=label or f'sSpriteDataRaw_{ROM_BASE+st:08X}'
        if name in used: raise E(f'duplicate label {name}')
        used.add(name)
        data=rom[st:en]
        if len(data)!=en-st: raise E(f'ROM too short for 0x{st:X}-0x{en:X}')
        c += [f'/* 0x{ROM_BASE+st:08X} - 0x{ROM_BASE+en:08X}: not yet typed. */',f'const u8 {name}[] = {{',fmt_bytes(data),'};','']
    # Rebuild suffix ASM cleanly, preserving labels and standard header.
    suffix_text=['.include "macros.s.inc"\n','\n','.section .rodata\n','\n']
    for st,en,label in suffix:
        if label:
            suffix_text += [f'.global {label}\n',f'{label}:\n','\n']
        suffix_text += [f'baserom_blob 0x{st:X}, 0x{en:X}\n','\n']
    object_basename = asm.with_suffix('.o').name
    object_re = re.compile(
        rf"(?P<object>(?:[A-Za-z0-9_.$(){{}}+-]+[/\\])*{re.escape(object_basename)})"
        rf"(?P<section>\s*\([^;\n]*\)\s*;)"
    )
    ltxt=a.linker.read_text() if a.linker.exists() else ''
    matches=list(object_re.finditer(ltxt))
    if len(matches)!=1:
        found=', '.join(m.group('object') for m in matches) or 'none'
        raise E(f'Expected exactly one linker token matching `{object_basename}`, found {len(matches)}: {found}')
    match=matches[0]
    old_obj=match.group('object')+match.group('section')
    existing_object=match.group('object').replace('\\','/')
    parts=existing_object.split('/')
    if 'obj' in parts:
        obj_root='/'.join(parts[:parts.index('obj')+1])
        new_object=f"{obj_root}/data/{out.with_suffix('').name}.o"
    else:
        new_object=f"obj/data/{out.with_suffix('').name}.o"
    new_obj=new_object+match.group('section')
    new_ltxt=ltxt[:match.start('object')]+new_obj+'\n        '+old_obj+ltxt[match.end('section'):]

    print(f'ASM prefix: 0x{ROM_BASE+start:08X}-0x{ROM_BASE+split:08X}')
    print(f'ASM suffix: 0x{ROM_BASE+split:08X}-0x{ROM_BASE+end:08X}')
    print(f'Generate: {out}')
    print(f'Linker insert: {new_obj} before {old_obj}')
    if not a.apply:
        print('Preview only. Re-run with --apply.')
        return
    backup=Path('build/oam_decode/backups/blob_split')
    for p in (asm,a.linker):
        dest=backup/p; dest.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(p,dest)
    out.parent.mkdir(parents=True,exist_ok=True)
    if out.exists(): raise E(f'Output already exists: {out}')
    out.write_text('\n'.join(c))
    asm.write_text(''.join(suffix_text))
    a.linker.write_text(new_ltxt)
    print('Applied successfully. Next run: python3 tools/decode_oam.py professor --apply')

if __name__=='__main__':
    try: main()
    except E as e:
        print(f'split_blob_region.py: error: {e}',file=sys.stderr); sys.exit(2)
